export const expenseConst = {
/*     SEARCH_TEXT: 'EXPENSE_SEARCH_TEXT',
    SEARCH_DATE: 'EXPENSE_SEARCH_DATE', */
    FETCH_ALL: 'EXPENSE_SEARCH_ALL',
    SEARCH_RESULTS: 'EXPENSE_SEARCH_RESULTS',
    CLEAR_EXPENSES: 'EXPENSE_CLEAR_STATE',
    SET_EXPENSES: 'EXPENSE_SET_STATE',
    ADD: 'ADD_EXPENSE'
};