name: Deploy
on:
  push:
    branches:
    - master
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: CashTrack
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: CashTrack
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check out ct-data
      uses: actions/checkout@v3
      with:
        repository: mitchellscot/ct-data
        token: ${{ secrets.CHECKOUT_CT_DATA_TOKEN }}
        path: ./ct-data
    - name: Copy Appsettings.json
      run: cp ./ct-data/appsettings.json ./src/appsettings.json
    - name: Copy Appsettings.Development.json
      run: cp ./ct-data/appsettings.Development.json ./src/appsettings.Development.json
    - name: Copy Appsettings.Test.json
      run: cp ./ct-data/appsettings.Test.json ./src/appsettings.Test.json
    - name: Add Variables To Appsettings Files
      uses: microsoft/variable-substitution@v1
      with:
        files: '**/appsettings.json, **/appsettings.Development.json, **/appsettings.Test.json'
      env:
        AppSettings.Secret: ${{ secrets.SECRET }}
        AppSettings.ConnectionStrings.Development: ${{ secrets.CONNECTION_STRING }}
        AppSettings.ConnectionStrings.Test: ${{ secrets.CONNECTION_STRING }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Test
      working-directory: "${{ env.WORKING_DIRECTORY }}"
      run: dotnet test --no-restore --verbosity normal
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.cash_track_BB41 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
