name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v3
      - name: Check out ct-data
        uses: actions/checkout@v3
        with:
          repository: mitchellscot/ct-data
          token: ${{ secrets.CHECKOUT_CT_DATA_TOKEN }}
      - name: Create Appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/appsettings.json'
          files: './src/appsettings.Development.json'
          files: './Test/CashTrack.IntegrationTests/appsettings.Test.json'
        env:
          AppSettings.Secret: ${{ secrets.SECRET }}
          AppSettings.ConnectionStrings.Development: ${{ secrets.CONN_STRING }}
          AppSettings.ConnectionStrings.Test: ${{ secrets.CONN_STRING }}
          AppSettings.ConnectionStrings.Production: ${{ secrets.CONN_STRING }}
          AppSettings.CreateDb: ${{secrets.CREATEDB}}
          AppSettings.CsvFileDirectory: ${{secrets.CSV_DIR}}
      - name: Create Appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.DOTNET_ROOT}}\src\appsettings.json'
          files: '${{env.DOTNET_ROOT}}\src\appsettings.Development.json'
          files: '${{env.DOTNET_ROOT}}\Test\CashTrack.IntegrationTests\appsettings.Test.json'
        env:
          CosmosDbSettings:ServiceEndpoint: ${{ secrets.COSMOSDBSETTINGS_SERVICEENDPOINT }}
          CosmosDbSettings:AuthKey: ${{ secrets.COSMOSDBSETTINGS_AUTHKEY }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./src
        run: dotnet test --no-restore --verbosity normal